needsPackage "SimplicialComplexes"

n = 4
S = QQ[a_(1, 1, 1)..a_(n, 3, 4)]
R = S[x_(1, 1)..x_(n, 3)]

-- Constructing simplicial complex for n=4
-- bi/tri/quadrifocals pre-calculated using focals-generation.m2

spr = f -> select(support f, x -> index x < numgens R)

F = openIn "focals-n4.m2"
focals = value get F;
focals = delete(0, focals);
spreads = toList set for foc in focals list spr foc;

spreadMonomials = for spread in spreads list product spread;
spreadIdeal = monomialIdeal spreadMonomials;
Delta = simplicialComplex spreadIdeal;
isPure Delta -- true. Should be true for each of our ideals.
dim Delta -- 6. So all facets have 7 vertices => needs 7 slack variables in elimination.

facetsDelta = facets Delta;

-* Checking if any polynomial in the ideal generated by the bi/tri/quadrifocals has support in a facet of delta.
There exists f in vanishig ideal I  with spr f subset U iff subring generated by monomials in U has nonempty intersection with I. *-

A = S[x_(1, 1)..x_(n,3), y_1..y_7, MonomialOrder => Eliminate 12] -- Number of y variables = dim Delta

-- reload list of focals as elements of A

F = openIn "focals-n4.m2"
focals = value get F;
focals = delete(0, focals);
spreads = toList set for foc in focals list spr foc;

spreadMonomials = for spread in spreads list product spread;
spreadIdeal = monomialIdeal spreadMonomials;
Delta = simplicialComplex spreadIdeal;
facetsDelta = facets Delta;


facetIntersect = facet -> ( U = drop(support facet, -7); -- dropping slack variables
    rels = for i from 1 to 7 list (y_i - (U_(i-1)));
    Jgens = join(focals, rels);
    J = ideal Jgens;
    selectInSubring(1,gens gb J))

i=0 
intersections = for facet in facetsDelta list facetIntersect facet do (i=i+1;print i)
    
all (intersections, i -> i == 0) -- True. So no element of vanishing ideal has spread inside a facet of delta.

-- Follows that bi/tri/quadrifocals form a UGB.
