needsPackage "SimplicialComplexes"

n = 4
S = QQ[a_(1, 1, 1)..a_(n, 3, 4)]
R = S[x_(1, 1)..x_(n, 3)]

-- Constructing simplicial complex for n=4

spr = f -> select(support f, x -> index x < numgens R)

F = openIn "focals-n4.m2";
focals = value get F;
focals = delete(0, focals);
spreads = toList set for foc in focals list spr foc;

spreadMonomials = for spread in spreads list product spread;
spreadIdeal = monomialIdeal spreadMonomials;
Delta = simplicialComplex spreadIdeal;
isPure Delta -- true. Should be true for each of our ideals.
dim Delta -- 6. So all facets have 7 vertices => needs 7 slack variables in elimination.

facetsDelta = facets Delta;

-* Checking if any polynomial in the ideal generated by the bi/tri/quadrifocals has support in a facet of delta.
By Lemma 5.5, we need only check facets of the form W\cup{A} where W is a facet of Delta_4 with profile (3, 2, 1, 1) or (2, 2, 2, 1).
There exists f in vanishig ideal I  with spr f subset U iff subring generated by monomials in U has nonempty intersection with I. *-

A = QQ[a_(1, 1, 1)..a_(n, 3, 4), x_(1, 1)..x_(n,3), y_1..y_55, MonomialOrder => Eliminate 60] -- Number of y variables = dim Delta

-- Load list of focals as elements of A. Focals are pre-computed using focals-generation.m2

F = openIn "focals-n4.m2"
focals = value get F;
focals = delete(0, focals);

-- constructing facets of type (3,2,1,1) and (2,2,2,1) as elements of A

camVars = product(toList(a_(1,1,1)..a_(4,3,4)))

-- (3,2,1,1)

x1 = product(toList(x_(1,1)..x_(1,3)))
x2s = for s in subsets(toList(x_(2,1)..x_(2,3)), 2) list product(s)
x3s = toList(x_(3,1)..x_(3,3))
x4s = toList(x_(4,1)..x_(4,3))

f3211 = {}

for x2 in x2s do (for x3 in x3s do (for x4 in x4s do (f3211 = f3211 | {product({camVars,x1, x2, x3, x4})})))

-- (2,2,2,1)

x1s =  for s in subsets(toList(x_(1,1)..x_(1,3)), 2) list product(s)
x2s = for s in subsets(toList(x_(2,1)..x_(2,3)), 2) list product(s)
x3s = for s in subsets(toList(x_(3,1)..x_(3,3)), 2) list product(s)
x4s = toList(x_(4,1)..x_(4,3))

f2221 = {}

for x1 in x1s do(for x2 in x2s do (for x3 in x3s do(for x4 in x4s do(f2221 = f2221 | {product({camVars, x1, x2, x3,x4})}))))

universalfacets = f3211 | f2221;


facetIntersect = facet -> ( U = support facet;
    rels = for i from 1 to 55 list (y_i - (U_(i-1)));
    Jgens = join(focals, rels);
    J = ideal Jgens;
    selectInSubring(1,gens gb J))

i=0 
intersections = for facet in universalfacets list facetIntersect facet
    
all (intersections, i -> i == 0) -- True. So no element of vanishing ideal has spread inside a facet of delta.

-- Follows that bi/tri/quadrifocals form a UGB.
